/*
 * generated by Xtext 2.32.0
 */
package org.xtext.project.lsysgen.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.project.lsysgen.LSysGenRuntimeModule;
import org.xtext.project.lsysgen.LSysGenStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LSysGenIdeSetup extends LSysGenStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LSysGenRuntimeModule(), new LSysGenIdeModule()));
	}
	
}
